import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../services/ai/ai_service.dart';
import '../settings/settings_screen.dart' show kAiBackendUrlPrefKey;

class ConversationScreen extends StatefulWidget { const ConversationScreen({super.key, required this.ocrText, required this.imagePaths}); final String ocrText; final List<String> imagePaths; @override State<ConversationScreen> createState()=>_ConversationScreenState(); }
class _ConversationScreenState extends State<ConversationScreen>{final _input=TextEditingController();final _messages=<Map<String,String>>[];bool _busy=false;AiProvider? _ai;
@override void initState(){super.initState();_loadProvider();}
Future<void> _loadProvider() async {
  final prefs = await SharedPreferences.getInstance();
  final url = prefs.getString(kAiBackendUrlPrefKey);
  if (url != null && url.isNotEmpty && mounted) setState(() => _ai = BackendAiProvider(url));
}
Future<void> _ask(String q)async{if(q.trim().isEmpty)return;setState(()=>_busy=true);_messages.add({'role':'user','text':q});try{final answer=_ai==null?'AI backend is not configured yet. Add your endpoint URL in Settings → AI backend to enable AI conversation.':'${await _ai!.ask(ocrText:widget.ocrText,question:q)}';_messages.add({'role':'assistant','text':answer});}catch(_){_messages.add({'role':'assistant','text':'Could not reach the AI service. Check your internet connection.'});}finally{_input.clear();if(mounted)setState(()=>_busy=false);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Ask about image')),body:Column(children:[Expanded(child:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Theme.of(context).colorScheme.primaryContainer,borderRadius:BorderRadius.circular(20)),child:Text('I’ve analyzed ${widget.imagePaths.length} image${widget.imagePaths.length==1?'':'s'}. Ask anything about the detected text.')),const SizedBox(height:12),Wrap(spacing:8,runSpacing:8,children:['Extract text','Translate','Summarize','Extract dates','Extract names','Make a table'].map((s)=>ActionChip(label:Text(s),onPressed:()=>_ask(s))).toList()),..._messages.map((m)=>Align(alignment:m['role']=='user'?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(14),constraints:const BoxConstraints(maxWidth:330),decoration:BoxDecoration(color:m['role']=='user'?Theme.of(context).colorScheme.primary:Theme.of(context).colorScheme.surface, borderRadius:BorderRadius.circular(18)),child:Text(m['text']!,style:TextStyle(color:m['role']=='user'?Theme.of(context).colorScheme.onPrimary:null))))])),Padding(padding:const EdgeInsets.fromLTRB(12,6,12,16),child:Row(children:[Expanded(child:TextField(controller:_input,onSubmitted:_ask,decoration:const InputDecoration(hintText:'Ask anything about this image...'))),const SizedBox(width:8),IconButton.filled(onPressed:_busy?null:()=>_ask(_input.text),icon:_busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.arrow_upward_rounded))]))]));}
